### ISSUE TITLE
Setting myself admin

### ISSUE THREAD

**Issue by Moshikot3** [TheWhatsBot/WhatsBot#3]
how do i set my wa number as admin?

**Comment by cachecleanerjeet** [comment]
What? Didn't get u

**Comment by Moshikot3** [comment]
nope, i dont think so...

I started the bot with !start command, i get the starting message and then nothing.

bot is not responding to any command and no errors in terminal

**Comment by Moshikot3** [comment]
![image](https://user-images.githubusercontent.com/8211790/102722625-060abb80-430b-11eb-9bf7-085742fd0bb0.png)

**Comment by cachecleanerjeet** [comment]
Irrelevant issue,
